# ---- Base ----
FROM node:24.6.0-alpine AS base
WORKDIR /usr/src/app
RUN npm install -g pnpm@10.15.0

# ---- Dependencies ----
FROM base AS dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# ---- Dev ----
FROM dependencies AS dev
COPY . .
CMD ["pnpm", "dev"]
