export enum Permission {
	super = 'SUPER',
	user = 'USER',
	userProfile = 'USER_PROFILE',
	userAdd = 'USER_ADD',
	userRead = 'USER_READ',
	userReadOne = 'USER_READ_ONE',
	userUpdate = 'USER_UPDATE',
	userDelete = 'USER_DELETE',
	rol = 'ROL',
	rolAdd = 'ROL_ADD',
	rolRead = 'ROL_READ',
	rolReadOne = 'ROL_READ_ONE',
	rolUpdate = 'ROL_UPDATE',
	rolDelete = 'ROL_DELETE',
	audit = 'AUDIT',
	auditRead = 'AUDIT_READ',
	auditDelete = 'AUDIT_DELETE',
}
