name: Continuous Integration

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint # Asumo que tienes un script 'lint' en tu package.json

      - name: Run tests
        run: pnpm run test # Asumo que tienes un script 'test' en tu package.json

      - name: Build project
        run: pnpm run build
